---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls())
```

```{r}
load("/home/rstudio/working/Dropbox/WORK/LIFEGenMon/optimal_sampling/Simulations_adegenet/Optimal_Sampling_simulation_data/Abies/Abies_SL_Adult_100_repl_results.RData")
```

```{r SL_Ho_He, fig.height=4, fig.width=10, cache=T}
# First run the plots section from optimal_sampling.R

# Filter results for 3 loci classes

library(tidyverse)
library(RColorBrewer)
Hobs_means_tidy3 <- Hobs_means_tidy %>% 
  filter(marker_num %in% c('5 markers', '8 markers', '11 markers'))


my_palette <- brewer.pal(12, "Set3") # create a new palette
my_palette <- colorRampPalette(my_palette)(19) # how many colors this palette will have

y_axis_Ho <- seq(0.05, 0.95, 0.05)

p_Ho_tidy <- ggplot(Hobs_means_tidy3, aes(x = samp_size, y = value)) + 
  geom_boxplot(aes(fill = samp_size)) + 
  facet_wrap(~ marker_num, nrow = 1)

p_Ho_tidy + xlab("Sample Size") +
  scale_fill_manual(values = my_palette) +
  theme_classic() +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle=90, vjust=0.5)) + 
  theme(text = element_text(size = 18)) +
  theme(title = element_text(size = 18)) +
  scale_y_continuous(name = expression(paste(" ", H[o], "" )), 
                     breaks = y_axis_Ho) +
  stat_summary(fun.y=mean, geom="point", shape=4, size=2, color="black", fill="black")

# p_Ho




# He ----------------------------------------------------------------------

Hexp_means_tidy3 <- Hexp_means_tidy %>% 
  filter(marker_num %in% c('5 markers', '8 markers', '11 markers'))

y_axis_He <- seq(0.05, 0.95, 0.05)

p_He_tidy <- ggplot(Hexp_means_tidy3, aes(x = samp_size, y = value)) + 
  geom_boxplot(aes(fill = samp_size)) + 
  facet_wrap(~ marker_num, nrow = 1)

p_He_tidy + xlab("Sample Size") + 
  scale_fill_manual(values = my_palette) +
  theme_classic() +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle=90, vjust=0.5)) + 
  theme(text = element_text(size = 18)) +
  theme(title = element_text(size = 18)) +
  scale_y_continuous(name = expression(paste("",H[e],"") ), 
                     breaks = y_axis_He) +
  stat_summary(fun.y=mean, geom="point", shape=4, size=2, color="black", fill="black")

```

```{r fig.height=8, fig.width=10, cache=T}
# combine -----------------------------------------------------------------

# library(gridExtra)

# png("DE_A_Ho_He.png",
#     width = 720,
#     height = 1280,
#     units = "px")

# grid.arrange(p_Ho, p_He,                
#              ncol = 2, nrow = 2, 
#              layout_matrix = rbind(c(1,1), c(2,2)))

# dev.off()
```





```{r SL_Ar_perc, fig.height=4, fig.width=10, cache=T}

ar_means_tidy3 <- ar_means_tidy %>% 
  filter(marker_num %in% c('5 markers', '8 markers', '11 markers'))

y_axis_ar <- seq(6, 30, 2)

p_ar_tidy <- ggplot(ar_means_tidy3, aes(x = samp_size, y = value)) + 
  geom_boxplot(aes(fill = samp_size)) + 
  facet_wrap(~ marker_num, nrow = 1)

p_ar_tidy + xlab("Sample Size") +
  scale_fill_manual(values = my_palette) +
  theme_classic() +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle=90, vjust=0.5)) + 
  theme(text = element_text(size = 18)) +
  theme(title = element_text(size = 18)) +
  scale_y_continuous(name = "Ar", breaks = y_axis_ar) +
  stat_summary(fun.y=mean, geom="point", shape=4, size=2, color="black", fill="black")



perc_repl_detect3 <- perc_repl_detect %>% 
  filter(marker_num %in% c('5 markers', '8 markers', '11 markers'))


y_axis_perc <- seq(5, 100, 15)

p_perc <- ggplot(perc_repl_detect3, aes(x = samp_size, group = 1)) + 
  geom_point(aes(y = percent_f1, colour = "percent_f1")) + 
  geom_point(aes(y = percent_f2, colour = "percent_f2")) +
  geom_line(aes(y = percent_f1, colour = "percent_f1", linetype = "percent_f2")) + 
  geom_line(aes(y = percent_f2, colour = "percent_f2", linetype = "percent_f1")) +
  geom_hline(yintercept = 95, linetype = "dashed") + 
  facet_wrap(~ marker_num, nrow =1)

p_perc + xlab("Sample Size") +
  theme_classic() +
  theme(axis.text.x = element_text(angle=90, vjust=0.5)) + 
  theme(text = element_text(size = 18)) +
  theme(title = element_text(size = 18)) +
  scale_y_continuous(
    name = "Alleles detected (%)",
    breaks = y_axis_perc) +
  theme(legend.position = "none")




# grid.arrange(p_ar, p_perc3,                
#              ncol = 2, nrow = 2, 
#              layout_matrix = rbind(c(1,1), c(2,2)))


```

```{r}
rm(list=ls())
```






```{r}
load("/home/rstudio/working/Dropbox/WORK/LIFEGenMon/optimal_sampling/Simulations_adegenet/Optimal_Sampling_simulation_data/Abies_distances/Abies_SL_Adult_100_repl_differentiation_results.RData")
```

```{r SL_fst_dch, fig.height=4, fig.width=10, cache=T}
my_palette <- brewer.pal(12, "Set3") # create a new palette
my_palette <- colorRampPalette(my_palette)(19) # how many colors this palette will have

fst_tidy3 <- fst_tidy %>% 
  filter(marker_num %in% c('5 markers', '8 markers', '11 markers'))

y_axis_fst <- seq(-0.200, 0.950, 0.01)

p_fst_tidy <- ggplot(fst_tidy3, aes(x = samp_size, y = original_values)) +
geom_boxplot(aes(fill = samp_size)) +
facet_wrap(~ marker_num, nrow = 1)

p_fst_tidy + xlab("Sample Size") +
  scale_fill_manual(values = my_palette) +
  theme_classic() +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle=90, vjust=0.5)) + 
  theme(text = element_text(size = 18)) +
  theme(title = element_text(size = 18)) +
  scale_y_continuous(name = expression(paste("Mean pairwise ", F[ST])), breaks = y_axis_fst) +
  stat_summary(fun.y=mean, geom="point", shape=4, size=2, color="black", fill="black")



dch_tidy3 <- dch_tidy %>% 
  filter(marker_num %in% c('5 markers', '8 markers', '11 markers'))

y_axis_dch <- seq(-0.10, 0.95, 0.05)

p_dch_tidy <- ggplot(dch_tidy3, aes(x = samp_size, y = Dch)) +
  geom_boxplot(aes(fill = samp_size)) +
  facet_wrap(~ marker_num, nrow = 1)

p_dch_tidy + xlab("Sample Size") +
  scale_fill_manual(values = my_palette) +
  theme_classic() +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle=90, vjust=0.5)) + 
  theme(text = element_text(size = 18)) +
  theme(title = element_text(size = 18)) +
  scale_y_continuous(name = "Cavalli-Sforza Chord distance", breaks = y_axis_dch) +
  stat_summary(fun.y=mean, geom="point", shape=4, size=2, color="black", fill="black")




jost_tidy3 <- jost_tidy %>% 
  filter(marker_num %in% c('5 markers', '8 markers', '11 markers'))

y_axis_jost <- seq(-0.20, 0.95, 0.05)

p_jost_tidy <- ggplot(jost_tidy3, aes(x = samp_size, y = original_values)) +
  geom_boxplot(aes(fill = samp_size)) +
  facet_wrap(~ marker_num, nrow = 1)

p_jost_tidy + xlab("Sample Size") +
  scale_fill_manual(values = my_palette) +
  theme_classic() +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle=90, vjust=0.5)) + 
  theme(text = element_text(size = 18)) +
  theme(title = element_text(size = 18)) +
  scale_y_continuous(name = "Jost's D", breaks = y_axis_jost) +
  stat_summary(fun.y=mean, geom="point", shape=4, size=2, color="black", fill="black")
```

